CREATE DATABASE SQUID;
GO
USE SQUID;
GO
CREATE TABLE DEFAULTLOG(
	ID INT NOT NULL IDENTITY(1,1),
	TIME VARCHAR(50),
	DURATION VARCHAR(50),
	CLIENTADRESS VARCHAR(750),
	RESULTCODE VARCHAR(50),
	BYTES VARCHAR(50),
	REQUESTMETHOD VARCHAR(50),
	URL VARCHAR(750),
	USERREQUEST VARCHAR(750),
	HIERARCHYCODE VARCHAR(150),
	TYPE VARCHAR(150),
);
GO
INSERT INTO DEFAULTLOG(TIME, DURATION, CLIENT_ADRESS, RESULT_CODE, BYTES, REQUEST_METHOD, URL, USER_REQUEST,HIERARCHY_CODE,TYPE)
VALUES(@Time, @Duration, @ClientAdress, @ResultCode, @Bytes, @RequestMethod, @Url, @UserRequest, @HierarchyCode, @Type);