CREATE DATABASE SQUID;

USE SQUID;

CREATE TABLE DEFAULTLOG(
	ID INT NOT NULL IDENTITY(1,1),
	TIME VARCHAR(50),
	DURATION VARCHAR(50),
	CLIENT_ADRESS VARCHAR(260),
	RESULT_CODE VARCHAR(50),
	BYTES VARCHAR(50),
	REQUEST_METHOD VARCHAR(50),
	URL VARCHAR(260),
	USER_REQUEST VARCHAR(500),
	HIERARCHY_CODE VARCHAR(50),
	TYPE VARCHAR(150),
);

INSERT INTO DEFAULTLOG(TIME, DURATION, CLIENT_ADRESS, RESULT_CODE, BYTES, REQUEST_METHOD, URL, USER_REQUEST,HIERARCHY_CODE,TYPE)
VALUES(@Time, @Duration, @ClientAdress, @ResultCode, @Bytes, @RequestMethod, @Url, @UserRequest, @HierarchyCode, @Type);